from django.urls import path
from main_app import views

urlpatterns = [
    path('', views.login_page, name='login'),
    path('register/', views.register, name='register'),
    path('otp/', views.otp, name='otp'),
    path('resend_otp/', views.resend_otp, name='resend_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('pricing_plan/', views.pricing_plan, name='pricing_plan'),
    path('selected_plan/<slug:slug>/', views.selected_plan, name='selected_plan'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_books/', views.add_books, name='add_books'),
    path('add_department/', views.add_department, name='add_department'),
    path('add_events/', views.add_events, name='add_events'),
    path('add_exam/', views.add_exam, name='add_exam'),
    path('add_expenses/', views.add_expenses, name='add_expenses'),
    path('add_fees_collection/', views.add_fees_collection, name='add_fees_collection'),
    path('add_fees/', views.add_fees, name='add_fees'),
    path('add_holiday/', views.add_holiday, name='add_holiday'),
    path('add_room/', views.add_room, name='add_room'),
    path('add_salary/', views.add_salary, name='add_salary'),
    path('add_sports/', views.add_sports, name='add_sports'),
    path('add_student/', views.add_student, name='add_student'),
    path('add_subject/', views.add_subject, name='add_subject'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('add_time_table/', views.add_time_table, name='add_time_table'),
    path('add_transport/', views.add_transport, name='add_transport'),
    path('components/', views.components, name='components'),
    path('compose/', views.compose, name='compose'),
    path('data_tables/', views.data_tables, name='data_tables'),
    path('departments/', views.departments, name='departments'),
    path('edit_books/', views.edit_books, name='edit_books'),
    path('edit_department/', views.edit_departments, name='edit_department'),
    path('edit_exam/', views.edit_exam, name='edit_exam'),
    path('edit_fees/', views.edit_fees, name='edit_fees'),
    path('edit_room/', views.edit_room, name='edit_room'),
    path('edit_sports/', views.edit_sports, name='edit_sports'),
    path('edit_student/', views.edit_student, name='edit_student'),
    path('edit_subject/', views.edit_subject, name='edit_subject'),
    path('edit_teacher/', views.edit_teacher, name='edit_teacher'),
    path('edit_time_table/', views.edit_time_table, name='edit_time_table'),
    path('edit_transport/', views.edit_transport, name='edit_transport'),
    path('error_404/', views.error_404, name='error_404'),
    path('event/', views.event, name='event'),
    path('exam/', views.exam, name='exam'),
    path('expenses/', views.expenses, name='expenses'),
    path('fees_collections/', views.fees_collections, name='fees_collections'),
    path('fees/', views.fees, name='fees'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('form_basic_inputs/', views.form_basic_inputs, name='form_basic_inputs'),
    path('form_horizontal/', views.form_horizontal, name='form_horizontal'),
    path('form_input_groups/', views.form_input_groups, name='form_input_groups'),
    path('form_mask/', views.form_mask, name='form_mask'),
    path('form_validation/', views.form_validation, name='form_validation'),
    path('form_vertical/', views.form_vertical, name='form_vertical'),
    path('holiday/', views.holiday, name='holiday'),
    path('hostel/', views.hostel, name='hostel'),
    path('inbox/', views.inbox, name='inbox'),
    path('invoice/', views.invoice, name='invoice'),
    path('library/', views.library, name='library'),
    
    path('profile/', views.profile, name='profile'),
    path('salary/', views.salary, name='salary'),
    path('sports/', views.sports, name='sports'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('student_details/', views.student_details, name='student_details'),
    path('students/', views.students, name='students'),
    path('subjects/', views.subjects, name='subjects'),
    path('tables_basic/', views.tables_basic, name='tables_basic'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher_details/', views.teacher_details, name='teacher_details'),
    path('teachers/', views.teachers, name='teachers'),
    path('time_table/', views.time_table, name='time_table'),
    path('transport/', views.transport, name='transport'),
    path('blank_page/', views.blank_page, name='blank_page'),
    
    
]
